
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiipxymhxkhahudweseg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaXB4eW1oeGtoYWh1ZHdlc2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTQwODYsImV4cCI6MjA2MzQzMDA4Nn0.1rLlH2UH2TzppN3AS8WhLMSlby5o0AkWF631I7BxLMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
